plateforme_data_demo:
  target: dev
  outputs:
    dev:
      dataset: plateforme_data_demo_dev
      keyfile_json:
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        auth_uri: https://accounts.google.com/o/oauth2/auth
        client_email: "{{ env_var('KEYFILE_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('KEYFILE_CLIENT_ID') }}"
        client_x509_cert_url: "{{ env_var('KEYFILE_CLIENT_X509_CERT_URL') }}"
        private_key: "{{ env_var('KEYFILE_PRIVATE_KEY') }}"
        project_id: "{{ env_var('KEYFILE_PROJECT_ID') }}"
        token_uri: https://oauth2.googleapis.com/token
        type: service_account
      location: EU
      method: service-account-json
      project: "{{ env_var('KEYFILE_PROJECT_ID') }}"
      threads: 8
      type: bigquery 
      config:
        partial_parse: true

