name: Build de l'image Docker de DBT

on:
    workflow_call:

jobs:
    dbt_build_docker:
      name: Construction Image docker
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Log in to Google Artifact Registry
          uses: docker/login-action@v3
          with:
            registry: europe-west1-docker.pkg.dev
            username: _json_key
            password: ${{ secrets.GAR_JSON_KEY }}
  
        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./utils/docker/plateforme_data_demo_dbt
            push: true
            tags: europe-west1-docker.pkg.dev/plateforme-data-demo/effidic-registry/plateforme-data-demo-dbt:main